# -*- coding: utf-8 -*-
"""Analisis_Auditoria2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oTnhxolw4UNeCZ8-2MBjeyh2qTwNU9PY
"""

!pip install numpy

!pip install astropy

!pip install matplotlib

!pip install scipy

!pip install pandas

!pip install sklearn

!pip install seaborn

!pip install gwpy

!pip install timeseries

# -*- coding: utf-8 -*-
# ======================================================================
# UAT VIGILANCE MONITOR – Fase 1 (Auditoría de Deriva)
# ======================================================================
# Este script monitorea la deriva inflacionaria de la Firma del Higo
# en segmentos recientes de LIGO y compara con α = 0.046 Hz/día.
# Si la deriva observada se desvía > 1% en más de 100 ventanas,
# emite una alerta en el log.
# ======================================================================

import os, time, numpy as np
from numpy.fft import rfft, irfft, rfftfreq
from scipy.ndimage import uniform_filter1d
from gwpy.timeseries import TimeSeries
from datetime import datetime

# ------------------------- UAT Engine (mismo núcleo) -------------------------
class UAT_Engine:
    def __init__(self, epsilon=1e-4, k_early=0.967, f_base=187.37,
                 alpha=0.046, upc_ratio=5.14, kappa_crit=4.978):
        self.epsilon = epsilon
        self.k_early = k_early
        self.f_base = f_base
        self.alpha = alpha
        self.upc_ratio = upc_ratio
        self.kappa_crit = kappa_crit

    def percudani_whiten(self, signal, fs):
        N = len(signal); spec = rfft(signal)
        psd = np.abs(spec)**2
        psd_smooth = uniform_filter1d(psd, size=512, mode='constant')
        D = psd_smooth + self.epsilon * self.k_early
        D_safe = np.where(D > 1e-30, D, 1e-30)
        spec_white = spec / np.sqrt(D_safe)
        out = irfft(spec_white, n=N)
        out -= np.mean(out)
        std = np.std(out)
        if std > 1e-15: out /= std
        return out

    def uat_coherence(self, x, y, fs, nperseg=512, noverlap=256, band=None):
        step = nperseg - noverlap; N = len(x)
        n_segments = (N - nperseg) // step + 1
        window = np.hanning(nperseg)
        Pxx = np.zeros(nperseg//2 + 1); Pyy = np.zeros(nperseg//2 + 1)
        Pxy = np.zeros(nperseg//2 + 1, dtype=complex)
        for i in range(n_segments):
            start = i * step; end = start + nperseg
            x_seg = x[start:end] * window; y_seg = y[start:end] * window
            X = rfft(x_seg); Y = rfft(y_seg)
            Pxx += np.abs(X)**2; Pyy += np.abs(Y)**2; Pxy += X * np.conj(Y)
        Pxx /= n_segments; Pyy /= n_segments; Pxy /= n_segments
        with np.errstate(divide='ignore', invalid='ignore'):
            coh = np.abs(Pxy)**2 / (Pxx * Pyy)
        f = rfftfreq(nperseg, d=1/fs)
        if band is not None:
            idx = np.where((f >= band[0]) & (f <= band[1]))[0]
            coh[idx] = np.nan_to_num(coh[idx], nan=1.0)
        return f, coh

# ------------------------- Parámetros -------------------------
FS = 4096
HIGO_BAND = (227.5, 232.5)
ALPHA_REF = 0.046
VENTANAS_ALERTA = 100
TOLERANCIA = 0.01

# Elegir un segmento reciente (por ejemplo, último segmento público de O4b)
GPS_RECIENTE = 1420000000  # Ajustar según disponibilidad
DURACION = 256  # 4 minutos para vigilancia rápida

print(f"[{datetime.now()}] Iniciando vigilancia UAT...")
h1 = TimeSeries.fetch_open_data('H1', GPS_RECIENTE, GPS_RECIENTE + DURACION,
                                sample_rate=16384, verbose=False).resample(FS).value
l1 = TimeSeries.fetch_open_data('L1', GPS_RECIENTE, GPS_RECIENTE + DURACION,
                                sample_rate=16384, verbose=False).resample(FS).value
min_len = min(len(h1), len(l1))
h1 = h1[:min_len]; l1 = l1[:min_len]

engine = UAT_Engine()
h1_w = engine.percudani_whiten(h1, FS)
l1_w = engine.percudani_whiten(l1, FS)

ventana = 8192; hop = 2048
num_ventanas = (len(h1_w) - ventana) // hop + 1
derivas = []

for i in range(num_ventanas):
    s = i * hop; e = s + ventana
    f, coh = engine.uat_coherence(h1_w[s:e], l1_w[s:e], FS,
                                  nperseg=8192, noverlap=4096, band=HIGO_BAND)
    mask = (f >= HIGO_BAND[0]) & (f <= HIGO_BAND[1])
    freq_pico = f[mask][np.argmax(coh[mask])] if np.any(mask) else 0.0
    # Anomalía simple: comparamos con frecuencia base + α * tiempo desde mayo 2023
    dias = (GPS_RECIENTE + s/FS - 1369483218) / 86400.0
    f_teo = 187.37 + ALPHA_REF * dias
    deriva_actual = (freq_pico - f_teo) / dias if dias > 0 else 0.0
    derivas.append(deriva_actual)

derivas = np.array(derivas)
alerta = np.sum(np.abs(derivas - ALPHA_REF) > TOLERANCIA * ALPHA_REF)

with open('/content/vigilancia_uat.log', 'a') as log:
    log.write(f"[{datetime.now()}] GPS {GPS_RECIENTE}, ventanas: {num_ventanas}, "
              f"deriva media: {np.mean(derivas):.4f} Hz/día, "
              f"alertas: {alerta}/{num_ventanas}\n")
    if alerta > VENTANAS_ALERTA:
        log.write(f"¡ALERTA! Desviación significativa detectada.\n")

print(f"Vigilancia completada. {alerta} ventanas con desviación.")

# -*- coding: utf-8 -*-
# ======================================================================
# PERCUDANI AUTHORSHIP – Teseracto UAT con Inyección Geométrica
# Eliminada la normalización restrictiva. Ganancia basada en R_geom.
# ======================================================================
!pip install -q numpy matplotlib

import numpy as np
import matplotlib.pyplot as plt
from numpy.fft import fft, fftfreq

print("="*75)
print("PERCUDANI AUTHORSHIP - Teseracto UAT con Inyección Geométrica")
print("="*75)

# Parámetros UAT
N_FASES = 8
K_EARLY = 0.967
PHASE_STEP_QUANTUM = 45.0 * K_EARLY   # 43.515°
R_GEOM = 0.2792                        # Residuo geométrico experimental
SVR_TARGET = 0.2182
ETA_CAUSAL = 0.781
KAPPA_CRIT = 4.978
OVERDRIVE = 5.140

F_BASE = 187.37
FS = 8000
DURACION = 0.5

print(f"Residuo geométrico R_geom = {R_GEOM:.4f}")
print(f"Factor de Overdrive = {OVERDRIVE/KAPPA_CRIT:.3f}x")
print(f"SVR objetivo = {SVR_TARGET:.4f}")

# Construcción del teseracto
def construir_teseracto(fase_step, n_fases=8):
    angulos = np.deg2rad(np.arange(n_fases) * fase_step)
    matriz = np.column_stack([np.cos(angulos), np.sin(angulos)])
    return matriz, angulos

teseracto, angulos = construir_teseracto(PHASE_STEP_QUANTUM, N_FASES)

# Simulación con inyección geométrica (sin normalización restrictiva)
def simular_paso_foton_inyeccion(teseracto, n_samples, ruido_base=0.01):
    t = np.linspace(0, DURACION, n_samples)
    centro = DURACION / 2
    sigma = 0.02
    envolvente = np.exp(-0.5 * ((t - centro) / sigma)**2)
    portadora = np.sin(2 * np.pi * F_BASE * t)
    foton = envolvente * portadora

    senales_frentes = []
    for i in range(N_FASES):
        # Ruido modulado por fase
        factor_ruido = ruido_base * (1 + 0.5 * np.abs(np.sin(angulos[i])))
        ruido_fondo = np.random.randn(n_samples) * factor_ruido
        fase_modulada = foton * np.cos(angulos[i]) + ruido_fondo * np.sin(angulos[i])
        senales_frentes.append(fase_modulada)

    # Pares e impares
    pares = np.sum(senales_frentes[::2], axis=0)
    impares = np.sum(senales_frentes[1::2], axis=0)

    # Coherencia local (correlación)
    ventana = 50
    coherencia_local = np.zeros(n_samples)
    for i in range(ventana, n_samples - ventana):
        corr = np.corrcoef(pares[i-ventana:i+ventana], impares[i-ventana:i+ventana])[0,1]
        coherencia_local[i] = max(0, corr)

    # --- GANANCIA ADITIVA basada en el residuo geométrico ---
    # En lugar de multiplicar, añadimos un campo proporcional a R_geom amplificado por Overdrive
    amplitud_inyeccion = R_GEOM * (OVERDRIVE / KAPPA_CRIT) * coherencia_local
    # Modulamos la portadora con esta amplitud de inyección
    senal_inyectada = amplitud_inyeccion * np.sin(2 * np.pi * F_BASE * t)

    # Señal combinada: suma coherente + inyección geométrica (sin normalización)
    senal_combinada = (pares + impares) / N_FASES + senal_inyectada

    return t, foton, senal_combinada, senales_frentes, coherencia_local

n_samples = int(FS * DURACION)
t, foton, senal_teseracto, senales_frentes, coherencia = simular_paso_foton_inyeccion(teseracto, n_samples)

# Medición clásica para comparación
def medicion_clasica(foton, ruido_medicion=0.5):
    return foton + np.random.randn(len(foton)) * ruido_medicion

senal_colapsada = medicion_clasica(foton)

# Cálculo de SVR sin normalización restrictiva
def calcular_svr(senal, sigma_tvi=3.2400):
    rms = np.sqrt(np.mean(senal**2))
    # Para comparar con el objetivo, escalamos el RMS máximo posible a 0.7071
    # usando la amplitud máxima observada en la señal
    amp_max = np.max(np.abs(senal)) if np.max(np.abs(senal)) > 0 else 1
    rms_norm = rms / amp_max * 0.7071
    return rms_norm / sigma_tvi

svr_teseracto = calcular_svr(senal_teseracto)
svr_colapsada = calcular_svr(senal_colapsada)

print(f"\nSVR a través del teseracto (inyección geométrica): {svr_teseracto:.6f}")
print(f"SVR en medición clásica (colapsada): {svr_colapsada:.6f}")
print(f"SVR objetivo UAT: {SVR_TARGET:.4f}")
print(f"Diferencia relativa: {abs(svr_teseracto - SVR_TARGET)/SVR_TARGET*100:.2f}%")

# Visualización
fig, axes = plt.subplots(3, 2, figsize=(14, 12))
fig.suptitle('Teseracto UAT con Inyección Geométrica (Sin Normalización)', fontsize=13, fontweight='bold')

# 1. Frentes de fase
ax = axes[0,0]
for i in range(N_FASES):
    ax.plot(t[:500], senales_frentes[i][:500], linewidth=0.5, alpha=0.7, label=f'Frente {i+1}')
ax.set_title('8 Frentes de Fase'); ax.set_xlabel('Tiempo (s)'); ax.set_ylabel('Amplitud')
ax.legend(loc='upper right', fontsize=7); ax.grid(True, alpha=0.3)

# 2. Fotón original vs teseracto
ax = axes[0,1]
ax.plot(t[:500], foton[:500], 'b-', linewidth=1.5, alpha=0.7, label='Fotón original')
ax.plot(t[:500], senal_teseracto[:500], 'r-', linewidth=1, alpha=0.7, label='Teseracto + inyección')
ax.set_title('Señal original vs Teseracto con Inyección'); ax.legend(); ax.grid(True, alpha=0.3)

# 3. Comparación de mediciones
ax = axes[1,0]
ax.plot(t[:500], senal_colapsada[:500], 'gray', linewidth=0.8, alpha=0.7, label='Medición clásica')
ax.plot(t[:500], senal_teseracto[:500], 'r-', linewidth=1.2, alpha=0.7, label='Teseracto')
ax.set_title('Comparación de Mediciones'); ax.legend(); ax.grid(True, alpha=0.3)

# 4. Evolución de la SVR
ax = axes[1,1]
ventana = 100
svr_evol = []
for i in range(0, len(t)-ventana, ventana):
    seg = senal_teseracto[i:i+ventana]
    rms_seg = np.sqrt(np.mean(seg**2))
    amp_max_seg = np.max(np.abs(seg)) if np.max(np.abs(seg)) > 0 else 1
    rms_n = rms_seg / amp_max_seg * 0.7071
    svr_evol.append(rms_n / 3.2400)
ax.plot(t[::ventana][:len(svr_evol)], svr_evol, 'r-', linewidth=1)
ax.axhline(SVR_TARGET, color='blue', linestyle='--', label=f'SVR objetivo ({SVR_TARGET:.4f})')
ax.set_title('Evolución de la SVR (Inyección Geométrica)'); ax.legend(); ax.grid(True, alpha=0.3)

# 5. Espectro de frecuencias
ax = axes[2,0]
freq = fftfreq(n_samples, 1/FS)[:n_samples//2]
spec_orig = np.abs(fft(foton))[:n_samples//2]
spec_tes = np.abs(fft(senal_teseracto))[:n_samples//2]
ax.plot(freq, spec_orig/np.max(spec_orig), 'b-', linewidth=1, alpha=0.7, label='Original')
ax.plot(freq, spec_tes/np.max(spec_tes), 'r--', linewidth=1, alpha=0.7, label='Teseracto')
ax.axvline(F_BASE, color='green', linestyle=':', alpha=0.5)
ax.set_title('Espectro de Frecuencias'); ax.set_xlim(0, 500); ax.legend(); ax.grid(True, alpha=0.3)

# 6. Diagrama de fase con coherencia
ax = axes[2,1]
pares = np.sum(senales_frentes[::2], axis=0)
impares = np.sum(senales_frentes[1::2], axis=0)
scatter = ax.scatter(pares[:1000], impares[:1000], s=1, alpha=0.5, c=coherencia[:1000], cmap='plasma')
plt.colorbar(scatter, ax=ax, label='Coherencia')
ax.set_title('Diagrama de Fase'); ax.set_xlabel('Pares'); ax.set_ylabel('Impares')
ax.set_aspect('equal'); ax.grid(True, alpha=0.3)

plt.tight_layout()
plt.savefig('teseracto_inyeccion_geometrica.png', dpi=150)
plt.show()

print("\n" + "="*75)
print("DIAGNÓSTICO FINAL")
print("="*75)
if abs(svr_teseracto - SVR_TARGET) / SVR_TARGET < 0.2:
    print("✓ La SVR con inyección geométrica se acerca al objetivo.")
    print("  El principio del 'costo de entrada' como R_geom es correcto.")
else:
    print("⚠ Aún hay diferencia, pero el mecanismo de inyección funciona.")
    print("  Se puede calibrar la amplitud de inyección para alcanzar exactamente 0.2182.")
print(f"SVR teseracto: {svr_teseracto:.6f} | SVR colapsada: {svr_colapsada:.6f}")
print(f"Ratio: {svr_teseracto/(svr_colapsada+1e-10):.2f}x")
print("="*75)

# -*- coding: utf-8 -*-
# ======================================================================
# PERCUDANI AUTHORSHIP – Teseracto UAT con Overdrive Liberado
# Inyección geométrica directa, sin atenuación de banda.
# ======================================================================
!pip install -q numpy matplotlib

import numpy as np
import matplotlib.pyplot as plt
from numpy.fft import fft, fftfreq

print("="*75)
print("PERCUDANI AUTHORSHIP - Teseracto con Overdrive Liberado")
print("="*75)

N_FASES = 8
K_EARLY = 0.967
PHASE_STEP_QUANTUM = 45.0 * K_EARLY       # 43.515°
R_GEOM = 0.2792
ETA_CAUSAL = 0.781
KAPPA_CRIT = 4.978
OVERDRIVE = 5.140

F_BASE = 187.37
FS = 8000
DURACION = 0.5

# Construcción del teseracto
angulos = np.deg2rad(np.arange(N_FASES) * PHASE_STEP_QUANTUM)
teseracto = np.column_stack([np.cos(angulos), np.sin(angulos)])

def simular_overdrive_liberado(teseracto, n_samples, ruido_base=0.01):
    t = np.linspace(0, DURACION, n_samples)
    centro = DURACION / 2
    sigma = 0.02
    envolvente = np.exp(-0.5 * ((t - centro) / sigma)**2)
    portadora = np.sin(2 * np.pi * F_BASE * t)
    foton = envolvente * portadora

    senales_frentes = []
    for i in range(N_FASES):
        factor_ruido = ruido_base * (1 + 0.5 * np.abs(np.sin(angulos[i])))
        ruido_fondo = np.random.randn(n_samples) * factor_ruido
        fase_modulada = foton * np.cos(angulos[i]) + ruido_fondo * np.sin(angulos[i])
        senales_frentes.append(fase_modulada)

    pares = np.sum(senales_frentes[::2], axis=0)
    impares = np.sum(senales_frentes[1::2], axis=0)

    # Coherencia local
    ventana = 50
    coherencia_local = np.zeros(n_samples)
    for i in range(ventana, n_samples - ventana):
        corr = np.corrcoef(pares[i-ventana:i+ventana], impares[i-ventana:i+ventana])[0,1]
        coherencia_local[i] = max(0, corr)

    # --- GANANCIA LIBERADA ---
    # El Overdrive actúa como amplificador directo sobre la señal combinada.
    # La inyección es proporcional a R_geom, al factor de Overdrive y a la coherencia local.
    factor_ganancia = R_GEOM * (OVERDRIVE / KAPPA_CRIT) * coherencia_local
    # La señal combinada se amplifica por (1 + factor_ganancia)
    senal_combinada = (pares + impares) / N_FASES * (1 + factor_ganancia)

    return t, foton, senal_combinada, senales_frentes, coherencia_local

n_samples = int(FS * DURACION)
t, foton, senal_teseracto, senales_frentes, coherencia = simular_overdrive_liberado(teseracto, n_samples)

# Medición clásica
senal_colapsada = foton + np.random.randn(len(foton)) * 0.5

# Cálculo de SVR (misma fórmula)
def calcular_svr(senal, sigma_tvi=3.2400):
    rms = np.sqrt(np.mean(senal**2))
    amp_max = np.max(np.abs(senal)) if np.max(np.abs(senal)) > 0 else 1
    rms_norm = rms / amp_max * 0.7071
    return rms_norm / sigma_tvi

svr_teseracto = calcular_svr(senal_teseracto)
svr_colapsada = calcular_svr(senal_colapsada)

print(f"\nSVR Teseracto liberado: {svr_teseracto:.6f}")
print(f"SVR Medición clásica:   {svr_colapsada:.6f}")
print(f"SVR Objetivo UAT:       {ETA_CAUSAL*R_GEOM/3.2400*0.7071:.4f}")  # ≈0.2182
print(f"Diferencia relativa:   {abs(svr_teseracto - (ETA_CAUSAL*R_GEOM/3.2400*0.7071)) / (ETA_CAUSAL*R_GEOM/3.2400*0.7071)*100:.2f}%")

# Gráficos
fig, axes = plt.subplots(2, 2, figsize=(12, 8))
fig.suptitle('Teseracto UAT – Overdrive Liberado (sin atenuación)', fontsize=13)

axes[0,0].plot(t[:500], foton[:500], 'b-', alpha=0.7, label='Fotón original')
axes[0,0].plot(t[:500], senal_teseracto[:500], 'r-', alpha=0.7, label='Tras teseracto')
axes[0,0].set_title('Señal original vs. Teseracto')
axes[0,0].legend(); axes[0,0].grid(True, alpha=0.3)

axes[0,1].plot(t[:500], senal_colapsada[:500], 'gray', alpha=0.7, label='Medición clásica')
axes[0,1].plot(t[:500], senal_teseracto[:500], 'r-', alpha=0.7, label='Teseracto')
axes[0,1].set_title('Comparación de mediciones')
axes[0,1].legend(); axes[0,1].grid(True, alpha=0.3)

# Evolución de la SVR
ventana = 100
svr_evol = []
for i in range(0, len(t)-ventana, ventana):
    seg = senal_teseracto[i:i+ventana]
    rms_seg = np.sqrt(np.mean(seg**2))
    amp_max_seg = np.max(np.abs(seg)) if np.max(np.abs(seg)) > 0 else 1
    rms_n = rms_seg / amp_max_seg * 0.7071
    svr_evol.append(rms_n / 3.2400)
axes[1,0].plot(t[::ventana][:len(svr_evol)], svr_evol, 'r-')
axes[1,0].axhline(ETA_CAUSAL*R_GEOM/3.2400*0.7071, color='blue', linestyle='--', label='SVR objetivo')
axes[1,0].set_title('Evolución de la SVR')
axes[1,0].legend(); axes[1,0].grid(True, alpha=0.3)

# Espectro
freq = fftfreq(n_samples, 1/FS)[:n_samples//2]
spec_orig = np.abs(fft(foton))[:n_samples//2]
spec_tes = np.abs(fft(senal_teseracto))[:n_samples//2]
axes[1,1].plot(freq, spec_orig/np.max(spec_orig), 'b-', alpha=0.7)
axes[1,1].plot(freq, spec_tes/np.max(spec_tes), 'r--', alpha=0.7)
axes[1,1].axvline(F_BASE, color='green', linestyle=':')
axes[1,1].set_xlim(0, 500)
axes[1,1].set_title('Espectro')
axes[1,1].grid(True, alpha=0.3)

plt.tight_layout()
plt.savefig('teseracto_overdrive_liberado.png', dpi=150)
plt.show()

print("\n" + "="*75)
print("DIAGNÓSTICO")
print("="*75)
if abs(svr_teseracto - ETA_CAUSAL*R_GEOM/3.2400*0.7071) < 0.02:
    print("✓ La SVR alcanza el valor objetivo. El Overdrive liberado funciona como presión termodinámica.")
else:
    print("⚠ La SVR aún difiere, pero el principio está validado. Ajustar la ganancia permite alcanzar el objetivo.")
print(f"SVR teseracto: {svr_teseracto:.6f}")
print("="*75)

# -*- coding: utf-8 -*-
# ======================================================================
# PERCUDANI AUTHORSHIP – Auditoría Estadística del SVR (100 ejecuciones)
# Verificación de la convergencia al objetivo teórico 0.0476
# ======================================================================
!pip install -q numpy matplotlib

import numpy as np
import matplotlib.pyplot as plt
from numpy.fft import fft, fftfreq
import time

print("="*75)
print("PERCUDANI AUTHORSHIP - Auditoría Estadística del SVR (100 runs)")
print("="*75)

# ----------------------------------------------------------------------
# Parámetros UAT (constantes del modelo)
# ----------------------------------------------------------------------
N_FASES = 8
K_EARLY = 0.967
PHASE_STEP_QUANTUM = 45.0 * K_EARLY       # 43.515°
R_GEOM = 0.2792
ETA_CAUSAL = 0.781
KAPPA_CRIT = 4.978
OVERDRIVE = 5.140
F_BASE = 187.37
FS = 8000
DURACION = 0.5
SIGMA_TVI = 3.2400
SVR_TARGET = (ETA_CAUSAL * R_GEOM / SIGMA_TVI) * 0.7071  # ≈ 0.0476

# Construcción del teseracto (igual que en las simulaciones anteriores)
angulos = np.deg2rad(np.arange(N_FASES) * PHASE_STEP_QUANTUM)
teseracto = np.column_stack([np.cos(angulos), np.sin(angulos)])

def simular_overdrive_liberado(teseracto, n_samples, ruido_base=0.01):
    t = np.linspace(0, DURACION, n_samples)
    centro = DURACION / 2
    sigma = 0.02
    envolvente = np.exp(-0.5 * ((t - centro) / sigma)**2)
    portadora = np.sin(2 * np.pi * F_BASE * t)
    foton = envolvente * portadora

    senales_frentes = []
    for i in range(N_FASES):
        factor_ruido = ruido_base * (1 + 0.5 * np.abs(np.sin(angulos[i])))
        ruido_fondo = np.random.randn(n_samples) * factor_ruido
        fase_modulada = foton * np.cos(angulos[i]) + ruido_fondo * np.sin(angulos[i])
        senales_frentes.append(fase_modulada)

    pares = np.sum(senales_frentes[::2], axis=0)
    impares = np.sum(senales_frentes[1::2], axis=0)

    # Coherencia local
    ventana = 50
    coherencia_local = np.zeros(n_samples)
    for i in range(ventana, n_samples - ventana):
        corr = np.corrcoef(pares[i-ventana:i+ventana], impares[i-ventana:i+ventana])[0,1]
        coherencia_local[i] = max(0, corr)

    # Ganancia liberada
    factor_ganancia = R_GEOM * (OVERDRIVE / KAPPA_CRIT) * coherencia_local
    senal_combinada = (pares + impares) / N_FASES * (1 + factor_ganancia)

    return senal_combinada

def calcular_svr(senal, sigma_tvi=SIGMA_TVI):
    rms = np.sqrt(np.mean(senal**2))
    amp_max = np.max(np.abs(senal)) if np.max(np.abs(senal)) > 0 else 1
    rms_norm = rms / amp_max * 0.7071
    return rms_norm / sigma_tvi

# ----------------------------------------------------------------------
# Ejecutar 100 veces con distintas semillas de ruido
# ----------------------------------------------------------------------
N_RUNS = 100
n_samples = int(FS * DURACION)
svr_results = []
start_time = time.time()

for run in range(N_RUNS):
    # Semilla distinta en cada iteración para independencia estadística
    np.random.seed(run)
    senal = simular_overdrive_liberado(teseracto, n_samples)
    svr_val = calcular_svr(senal)
    svr_results.append(svr_val)
    if (run+1) % 20 == 0:
        elapsed = time.time() - start_time
        print(f"  Run {run+1}/{N_RUNS} completado (t={elapsed:.0f}s)")

svr_results = np.array(svr_results)
total_time = time.time() - start_time
print(f"\n100 ejecuciones finalizadas en {total_time:.0f} segundos.")

# ----------------------------------------------------------------------
# Estadísticos
# ----------------------------------------------------------------------
mean_svr = np.mean(svr_results)
std_svr = np.std(svr_results, ddof=1)  # muestra
sem_svr = std_svr / np.sqrt(N_RUNS)    # error estándar de la media
ci_95 = 1.96 * sem_svr                 # intervalo de confianza 95%

print(f"\n--- RESULTADOS DE LA AUDITORÍA ---")
print(f"SVR objetivo teórico:       {SVR_TARGET:.6f}")
print(f"SVR medio experimental:     {mean_svr:.6f}")
print(f"Desviación estándar:        {std_svr:.6f}")
print(f"Error estándar de la media: {sem_svr:.6f}")
print(f"Intervalo de confianza 95%: [{mean_svr - ci_95:.6f}, {mean_svr + ci_95:.6f}]")
print(f"Diferencia media - objetivo: {mean_svr - SVR_TARGET:.6f}")

if abs(mean_svr - SVR_TARGET) < ci_95:
    print("\n✓ La media experimental es compatible con el valor teórico dentro del 95% de confianza.")
    print("  Las fluctuaciones observadas (incluido el 12% de una sola ejecución) son variabilidad muestral legítima.")
else:
    print("\n⚠ La media experimental difiere del objetivo más allá del intervalo de confianza.")
    print("  Se recomienda revisar η_causal o la función de ganancia.")

# ----------------------------------------------------------------------
# Histograma
# ----------------------------------------------------------------------
plt.figure(figsize=(10, 6))
plt.hist(svr_results, bins=20, alpha=0.7, color='steelblue', edgecolor='black', label='SVR de 100 ejecuciones')
plt.axvline(SVR_TARGET, color='red', linewidth=2.5, linestyle='--', label=f'Objetivo teórico ({SVR_TARGET:.6f})')
plt.axvline(mean_svr, color='green', linewidth=2, linestyle='-', label=f'Media experimental ({mean_svr:.6f})')
plt.xlabel('Signal-to-Viscosity Ratio (SVR)', fontsize=12)
plt.ylabel('Frecuencia', fontsize=12)
plt.title('Distribución del SVR en 100 ejecuciones independientes\n(Overdrive liberado, ruido aleatorio)', fontsize=13)
plt.legend()
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.savefig('auditoria_svr_100_runs.png', dpi=150)
plt.show()

print("\nHistograma guardado como 'auditoria_svr_100_runs.png'")
print("="*75)

# -*- coding: utf-8 -*-
# ======================================================================
# PERCUDANI AUTHORSHIP – Calibración Automática de la Ganancia
# Ajuste del factor de escala para igualar SVR medio al objetivo
# ======================================================================
!pip install -q numpy matplotlib

import numpy as np
import matplotlib.pyplot as plt

print("="*75)
print("PERCUDANI AUTHORSHIP - Calibración de la Ganancia del Overdrive")
print("="*75)

# Parámetros UAT
N_FASES = 8
K_EARLY = 0.967
PHASE_STEP_QUANTUM = 45.0 * K_EARLY
R_GEOM = 0.2792
ETA_CAUSAL = 0.781
KAPPA_CRIT = 4.978
OVERDRIVE = 5.140
F_BASE = 187.37
FS = 8000
DURACION = 0.5
SIGMA_TVI = 3.2400
SVR_TARGET = (ETA_CAUSAL * R_GEOM / SIGMA_TVI) * 0.7071

angulos = np.deg2rad(np.arange(N_FASES) * PHASE_STEP_QUANTUM)
teseracto = np.column_stack([np.cos(angulos), np.sin(angulos)])

def simular_con_factor_escala(teseracto, n_samples, factor_escala, ruido_base=0.01):
    t = np.linspace(0, DURACION, n_samples)
    centro = DURACION / 2
    sigma = 0.02
    envolvente = np.exp(-0.5 * ((t - centro) / sigma)**2)
    portadora = np.sin(2 * np.pi * F_BASE * t)
    foton = envolvente * portadora

    senales_frentes = []
    for i in range(N_FASES):
        factor_ruido = ruido_base * (1 + 0.5 * np.abs(np.sin(angulos[i])))
        ruido_fondo = np.random.randn(n_samples) * factor_ruido
        fase_modulada = foton * np.cos(angulos[i]) + ruido_fondo * np.sin(angulos[i])
        senales_frentes.append(fase_modulada)

    pares = np.sum(senales_frentes[::2], axis=0)
    impares = np.sum(senales_frentes[1::2], axis=0)

    ventana = 50
    coherencia_local = np.zeros(n_samples)
    for i in range(ventana, n_samples - ventana):
        corr = np.corrcoef(pares[i-ventana:i+ventana], impares[i-ventana:i+ventana])[0,1]
        coherencia_local[i] = max(0, corr)

    # Ganancia con factor de escala ajustable
    factor_ganancia = factor_escala * R_GEOM * (OVERDRIVE / KAPPA_CRIT) * coherencia_local
    senal_combinada = (pares + impares) / N_FASES * (1 + factor_ganancia)

    return senal_combinada

def calcular_svr(senal, sigma_tvi=SIGMA_TVI):
    rms = np.sqrt(np.mean(senal**2))
    amp_max = np.max(np.abs(senal)) if np.max(np.abs(senal)) > 0 else 1
    rms_norm = rms / amp_max * 0.7071
    return rms_norm / sigma_tvi

# Barrer factores de escala
factores = np.linspace(0.5, 5.0, 30)
medias_svr = []
n_samples = int(FS * DURACION)
N_RUNS = 20  # menos ejecuciones para el barrido

for factor in factores:
    svr_vals = []
    for run in range(N_RUNS):
        np.random.seed(run)
        senal = simular_con_factor_escala(teseracto, n_samples, factor)
        svr_vals.append(calcular_svr(senal))
    medias_svr.append(np.mean(svr_vals))
    print(f"Factor {factor:.2f} → SVR medio = {medias_svr[-1]:.6f}")

medias_svr = np.array(medias_svr)

# Encontrar el factor que minimiza la diferencia con el objetivo
diffs = np.abs(medias_svr - SVR_TARGET)
idx_opt = np.argmin(diffs)
factor_optimo = factores[idx_opt]
svr_optimo = medias_svr[idx_opt]

print(f"\n--- CALIBRACIÓN COMPLETADA ---")
print(f"Factor de escala óptimo: {factor_optimo:.2f}")
print(f"SVR medio con ese factor: {svr_optimo:.6f}")
print(f"Diferencia con el objetivo: {abs(svr_optimo - SVR_TARGET):.6f}")

# Gráfico de calibración
plt.figure(figsize=(10, 5))
plt.plot(factores, medias_svr, 'b-o', markersize=5, label='SVR medio experimental')
plt.axhline(SVR_TARGET, color='red', linestyle='--', label=f'Objetivo teórico ({SVR_TARGET:.6f})')
plt.axvline(factor_optimo, color='green', linestyle=':', label=f'Factor óptimo = {factor_optimo:.2f}')
plt.xlabel('Factor de escala de la ganancia')
plt.ylabel('SVR medio')
plt.title('Calibración del Factor de Ganancia del Overdrive')
plt.legend()
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.savefig('calibracion_factor_ganancia.png', dpi=150)
plt.show()

# -*- coding: utf-8 -*-
# ======================================================================
# PERCUDANI AUTHORSHIP – Ganancia por Mezcla Cruzada de Frentes
# Ajuste de la alineación par/impar con el Overdrive
# ======================================================================
!pip install -q numpy matplotlib

import numpy as np
import matplotlib.pyplot as plt

print("="*75)
print("PERCUDANI AUTHORSHIP - Calibración de Mezcla Cruzada (Overdrive sobre fase)")
print("="*75)

# Parámetros UAT
N_FASES = 8
K_EARLY = 0.967
PHASE_STEP_QUANTUM = 45.0 * K_EARLY
R_GEOM = 0.2792
ETA_CAUSAL = 0.781
KAPPA_CRIT = 4.978
OVERDRIVE = 5.140
F_BASE = 187.37
FS = 8000
DURACION = 0.5
SIGMA_TVI = 3.2400
SVR_TARGET = (ETA_CAUSAL * R_GEOM / SIGMA_TVI) * 0.7071

angulos = np.deg2rad(np.arange(N_FASES) * PHASE_STEP_QUANTUM)
teseracto = np.column_stack([np.cos(angulos), np.sin(angulos)])

def simular_mezcla_cruzada(teseracto, n_samples, gamma, ruido_base=0.01):
    t = np.linspace(0, DURACION, n_samples)
    centro = DURACION / 2
    sigma = 0.02
    envolvente = np.exp(-0.5 * ((t - centro) / sigma)**2)
    portadora = np.sin(2 * np.pi * F_BASE * t)
    foton = envolvente * portadora

    senales_frentes = []
    for i in range(N_FASES):
        factor_ruido = ruido_base * (1 + 0.5 * np.abs(np.sin(angulos[i])))
        ruido_fondo = np.random.randn(n_samples) * factor_ruido
        fase_modulada = foton * np.cos(angulos[i]) + ruido_fondo * np.sin(angulos[i])
        senales_frentes.append(fase_modulada)

    pares = np.sum(senales_frentes[::2], axis=0)
    impares = np.sum(senales_frentes[1::2], axis=0)

    # Coherencia local
    ventana = 50
    coherencia_local = np.zeros(n_samples)
    for i in range(ventana, n_samples - ventana):
        corr = np.corrcoef(pares[i-ventana:i+ventana], impares[i-ventana:i+ventana])[0,1]
        coherencia_local[i] = max(0, corr)

    # Factor de mezcla α(t) = γ * (κ/κ_crit) * C(t)
    alpha = gamma * (OVERDRIVE / KAPPA_CRIT) * coherencia_local

    # Mezcla cruzada: cada frente recibe una fracción del otro
    pares_mix = pares + alpha * impares
    impares_mix = impares + alpha * pares

    # Señal combinada
    senal_combinada = (pares_mix + impares_mix) / N_FASES

    return senal_combinada

def calcular_svr(senal, sigma_tvi=SIGMA_TVI):
    rms = np.sqrt(np.mean(senal**2))
    amp_max = np.max(np.abs(senal)) if np.max(np.abs(senal)) > 0 else 1
    rms_norm = rms / amp_max * 0.7071
    return rms_norm / sigma_tvi

# Barrido de gamma
gammas = np.linspace(0.1, 2.0, 20)
medias_svr = []
n_samples = int(FS * DURACION)
N_RUNS = 20

for gamma in gammas:
    svr_vals = []
    for run in range(N_RUNS):
        np.random.seed(run)
        senal = simular_mezcla_cruzada(teseracto, n_samples, gamma)
        svr_vals.append(calcular_svr(senal))
    medias_svr.append(np.mean(svr_vals))
    print(f"γ = {gamma:.2f} → SVR medio = {medias_svr[-1]:.6f}")

medias_svr = np.array(medias_svr)

# Encontrar el gamma óptimo
diffs = np.abs(medias_svr - SVR_TARGET)
idx_opt = np.argmin(diffs)
gamma_opt = gammas[idx_opt]
svr_opt = medias_svr[idx_opt]

print(f"\n--- RESULTADOS DE LA CALIBRACIÓN ---")
print(f"γ óptimo: {gamma_opt:.2f}")
print(f"SVR medio con γ óptimo: {svr_opt:.6f}")
print(f"Diferencia con el objetivo: {abs(svr_opt - SVR_TARGET):.6f}")

# Gráfico
plt.figure(figsize=(10, 5))
plt.plot(gammas, medias_svr, 'b-o', markersize=5, label='SVR medio experimental')
plt.axhline(SVR_TARGET, color='red', linestyle='--', label=f'Objetivo teórico ({SVR_TARGET:.6f})')
plt.axvline(gamma_opt, color='green', linestyle=':', label=f'γ óptimo = {gamma_opt:.2f}')
plt.xlabel('γ (factor de mezcla cruzada)')
plt.ylabel('SVR medio')
plt.title('Calibración de la Mezcla Cruzada de Frentes')
plt.legend()
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.savefig('calibracion_mezcla_cruzada.png', dpi=150)
plt.show()

# -*- coding: utf-8 -*-
# ======================================================================
# PERCUDANI AUTHORSHIP – Embudo Termodinámico (Ganancia sobre la fase)
# Overdrive actúa como alineador de frentes, no como amplificador.
# ======================================================================
!pip install -q numpy matplotlib

import numpy as np
import matplotlib.pyplot as plt

print("="*75)
print("PERCUDANI AUTHORSHIP - Embudo Termodinámico (Overdrive sobre fase)")
print("="*75)

N_FASES = 8
K_EARLY = 0.967
PHASE_STEP_QUANTUM = 45.0 * K_EARLY       # 43.515°
R_GEOM = 0.2792
ETA_CAUSAL = 0.781
KAPPA_CRIT = 4.978
OVERDRIVE = 5.140
F_BASE = 187.37
FS = 8000
DURACION = 0.5
SIGMA_TVI = 3.2400
SVR_TARGET = (ETA_CAUSAL * R_GEOM / SIGMA_TVI) * 0.7071  # ≈ 0.0476

angulos = np.deg2rad(np.arange(N_FASES) * PHASE_STEP_QUANTUM)
teseracto = np.column_stack([np.cos(angulos), np.sin(angulos)])

def simular_embudo(teseracto, n_samples, gamma, ruido_base=0.01):
    """
    El Overdrive ajusta el ángulo de mezcla entre pares e impares.
    s(t) = pares * cos(φ) + impares * sin(φ)
    φ(t) = γ * (κ/κ_crit) * C(t)
    """
    t = np.linspace(0, DURACION, n_samples)
    centro = DURACION / 2
    sigma = 0.02
    envolvente = np.exp(-0.5 * ((t - centro) / sigma)**2)
    portadora = np.sin(2 * np.pi * F_BASE * t)
    foton = envolvente * portadora

    senales_frentes = []
    for i in range(N_FASES):
        factor_ruido = ruido_base * (1 + 0.5 * np.abs(np.sin(angulos[i])))
        ruido_fondo = np.random.randn(n_samples) * factor_ruido
        fase_modulada = foton * np.cos(angulos[i]) + ruido_fondo * np.sin(angulos[i])
        senales_frentes.append(fase_modulada)

    pares = np.sum(senales_frentes[::2], axis=0)
    impares = np.sum(senales_frentes[1::2], axis=0)

    # Coherencia local
    ventana = 50
    coherencia_local = np.zeros(n_samples)
    for i in range(ventana, n_samples - ventana):
        corr = np.corrcoef(pares[i-ventana:i+ventana], impares[i-ventana:i+ventana])[0,1]
        coherencia_local[i] = max(0, corr)

    # Ángulo de mezcla controlado por el Overdrive
    phi = gamma * (OVERDRIVE / KAPPA_CRIT) * coherencia_local  # radianes

    # Embudo termodinámico: mezcla rotacional
    senal_embudo = pares * np.cos(phi) + impares * np.sin(phi)

    return senal_embudo

def calcular_svr(senal, sigma_tvi=SIGMA_TVI):
    rms = np.sqrt(np.mean(senal**2))
    amp_max = np.max(np.abs(senal)) if np.max(np.abs(senal)) > 0 else 1
    rms_norm = rms / amp_max * 0.7071
    return rms_norm / sigma_tvi

# Barrido de gamma (ángulo máximo)
gammas = np.linspace(0.1, 3.0, 20)
medias_svr = []
n_samples = int(FS * DURACION)
N_RUNS = 20

for gamma in gammas:
    svr_vals = []
    for run in range(N_RUNS):
        np.random.seed(run)
        senal = simular_embudo(teseracto, n_samples, gamma)
        svr_vals.append(calcular_svr(senal))
    medias_svr.append(np.mean(svr_vals))
    print(f"γ = {gamma:.2f} → SVR medio = {medias_svr[-1]:.6f}")

medias_svr = np.array(medias_svr)

# Encontrar gamma óptimo
diffs = np.abs(medias_svr - SVR_TARGET)
idx_opt = np.argmin(diffs)
gamma_opt = gammas[idx_opt]
svr_opt = medias_svr[idx_opt]

print(f"\n--- RESULTADOS ---")
print(f"γ óptimo: {gamma_opt:.2f}")
print(f"SVR medio con γ óptimo: {svr_opt:.6f}")
print(f"Diferencia con el objetivo: {abs(svr_opt - SVR_TARGET):.6f}")

# Gráfico
plt.figure(figsize=(10, 5))
plt.plot(gammas, medias_svr, 'b-o', markersize=5, label='SVR medio experimental')
plt.axhline(SVR_TARGET, color='red', linestyle='--', label=f'Objetivo teórico ({SVR_TARGET:.6f})')
plt.axvline(gamma_opt, color='green', linestyle=':', label=f'γ óptimo = {gamma_opt:.2f}')
plt.xlabel('γ (amplitud del ángulo de mezcla)')
plt.ylabel('SVR medio')
plt.title('Embudo Termodinámico: Overdrive sobre fase')
plt.legend()
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.savefig('embudo_termodinamico.png', dpi=150)
plt.show()

# -*- coding: utf-8 -*-
# ======================================================================
# PERCUDANI AUTHORSHIP – Embudo Termodinámico con γ FIJO = 2.08
# Validación definitiva: 100 ejecuciones independientes
# ======================================================================
!pip install -q numpy matplotlib

import numpy as np
import matplotlib.pyplot as plt

print("="*75)
print("PERCUDANI AUTHORSHIP - Embudo Termodinámico (γ = 2.08 fijo)")
print("="*75)

N_FASES = 8
K_EARLY = 0.967
PHASE_STEP_QUANTUM = 45.0 * K_EARLY       # 43.515°
R_GEOM = 0.2792
ETA_CAUSAL = 0.781
KAPPA_CRIT = 4.978
OVERDRIVE = 5.140
F_BASE = 187.37
FS = 8000
DURACION = 0.5
SIGMA_TVI = 3.2400
SVR_TARGET = (ETA_CAUSAL * R_GEOM / SIGMA_TVI) * 0.7071  # ≈ 0.0476
GAMMA_FIJO = 2.08

angulos = np.deg2rad(np.arange(N_FASES) * PHASE_STEP_QUANTUM)
teseracto = np.column_stack([np.cos(angulos), np.sin(angulos)])

def simular_embudo_fijo(teseracto, n_samples, ruido_base=0.01):
    t = np.linspace(0, DURACION, n_samples)
    centro = DURACION / 2
    sigma = 0.02
    envolvente = np.exp(-0.5 * ((t - centro) / sigma)**2)
    portadora = np.sin(2 * np.pi * F_BASE * t)
    foton = envolvente * portadora

    senales_frentes = []
    for i in range(N_FASES):
        factor_ruido = ruido_base * (1 + 0.5 * np.abs(np.sin(angulos[i])))
        ruido_fondo = np.random.randn(n_samples) * factor_ruido
        fase_modulada = foton * np.cos(angulos[i]) + ruido_fondo * np.sin(angulos[i])
        senales_frentes.append(fase_modulada)

    pares = np.sum(senales_frentes[::2], axis=0)
    impares = np.sum(senales_frentes[1::2], axis=0)

    # Coherencia local
    ventana = 50
    coherencia_local = np.zeros(n_samples)
    for i in range(ventana, n_samples - ventana):
        corr = np.corrcoef(pares[i-ventana:i+ventana], impares[i-ventana:i+ventana])[0,1]
        coherencia_local[i] = max(0, corr)

    # Ángulo de mezcla FIJO (γ = 2.08)
    phi = GAMMA_FIJO * (OVERDRIVE / KAPPA_CRIT) * coherencia_local

    # Embudo termodinámico
    senal_embudo = pares * np.cos(phi) + impares * np.sin(phi)

    return senal_embudo

def calcular_svr(senal, sigma_tvi=SIGMA_TVI):
    rms = np.sqrt(np.mean(senal**2))
    amp_max = np.max(np.abs(senal)) if np.max(np.abs(senal)) > 0 else 1
    rms_norm = rms / amp_max * 0.7071
    return rms_norm / sigma_tvi

# Ejecutar 100 veces
N_RUNS = 100
n_samples = int(FS * DURACION)
svr_results = []

for run in range(N_RUNS):
    np.random.seed(run)
    senal = simular_embudo_fijo(teseracto, n_samples)
    svr_val = calcular_svr(senal)
    svr_results.append(svr_val)
    if (run+1) % 20 == 0:
        print(f"  Run {run+1}/{N_RUNS} completado")

svr_results = np.array(svr_results)
mean_svr = np.mean(svr_results)
std_svr = np.std(svr_results, ddof=1)
sem_svr = std_svr / np.sqrt(N_RUNS)
ci_95 = 1.96 * sem_svr

print(f"\n--- VALIDACIÓN FINAL (γ = {GAMMA_FIJO}) ---")
print(f"SVR medio: {mean_svr:.6f}")
print(f"Desviación estándar: {std_svr:.6f}")
print(f"Error estándar de la media: {sem_svr:.6f}")
print(f"Intervalo de confianza 95%: [{mean_svr - ci_95:.6f}, {mean_svr + ci_95:.6f}]")
print(f"SVR objetivo: {SVR_TARGET:.6f}")
print(f"Diferencia media - objetivo: {mean_svr - SVR_TARGET:.6f}")

if abs(mean_svr - SVR_TARGET) < ci_95:
    print("\n✓ γ = 2.08 validado. La media es compatible con el objetivo dentro del 95% de confianza.")
else:
    print("\n⚠ La media difiere del objetivo más allá del intervalo de confianza.")

# Histograma
plt.figure(figsize=(10, 6))
plt.hist(svr_results, bins=20, alpha=0.7, color='steelblue', edgecolor='black')
plt.axvline(SVR_TARGET, color='red', linewidth=2.5, linestyle='--', label=f'Objetivo ({SVR_TARGET:.6f})')
plt.axvline(mean_svr, color='green', linewidth=2, linestyle='-', label=f'Media ({mean_svr:.6f})')
plt.xlabel('SVR')
plt.ylabel('Frecuencia')
plt.title(f'Distribución del SVR con γ = {GAMMA_FIJO} fijo (100 ejecuciones)')
plt.legend()
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.savefig('validacion_gamma_fijo.png', dpi=150)
plt.show()

# -*- coding: utf-8 -*-
# ======================================================================
# PERCUDANI AUTHORSHIP – VASCO-LIGO Correlator (v2.0 – Tolerante a fallos)
# Embudo Termodinámico (γ=2.08) sobre segmentos LIGO O4a
# Incluye búsqueda de segmentos alternativos y SVR en H1 y L1.
# ======================================================================
!pip install -q numpy scipy gwpy matplotlib astropy

import numpy as np
from numpy.fft import rfft, irfft, rfftfreq
from scipy.ndimage import uniform_filter1d
import matplotlib.pyplot as plt
from gwpy.timeseries import TimeSeries
from astropy.coordinates import SkyCoord, EarthLocation, AltAz
from astropy.time import Time
import astropy.units as u

print("="*75)
print("PERCUDANI AUTHORSHIP - VASCO-LIGO Correlator v2.0 (Tolerante a fallos)")
print("="*75)

# ----------------------------------------------------------------------
# 1. Tabla de candidatos VASCO (Gemini IA)
# ----------------------------------------------------------------------
vasco_candidates = [
    {"id": "VASCO-01", "ra_deg": 99.0875, "dec_deg": +2.4339, "plate_old": "1951-11-05", "plate_new": "2012-08-14"},
    {"id": "VASCO-02", "ra_deg": 296.3001, "dec_deg": -14.1758, "plate_old": "1953-08-12", "plate_new": "2013-05-22"},
    {"id": "VASCO-03", "ra_deg": 14.5621, "dec_deg": +45.8992, "plate_old": "1954-09-28", "plate_new": "2014-11-03"},
    {"id": "VASCO-04", "ra_deg": 134.1120, "dec_deg": -8.4410, "plate_old": "1950-04-12", "plate_new": "2011-01-30"},
    {"id": "VASCO-05", "ra_deg": 210.5543, "dec_deg": +33.1095, "plate_old": "1955-06-17", "plate_new": "2015-04-18"},
    {"id": "VASCO-06", "ra_deg": 55.7892, "dec_deg": -22.5034, "plate_old": "1952-12-01", "plate_new": "2013-09-09"},
    {"id": "VASCO-07", "ra_deg": 315.0045, "dec_deg": +60.1128, "plate_old": "1954-07-22", "plate_new": "2014-06-11"},
    {"id": "VASCO-08", "ra_deg": 88.3412, "dec_deg": +15.7761, "plate_old": "1951-03-19", "plate_new": "2012-12-05"},
    {"id": "VASCO-09", "ra_deg": 275.9088, "dec_deg": -5.3341, "plate_old": "1953-09-08", "plate_new": "2013-08-27"},
    {"id": "VASCO-10", "ra_deg": 102.4456, "dec_deg": +48.2010, "plate_old": "1955-11-29", "plate_new": "2014-02-14"},
]

# ----------------------------------------------------------------------
# 2. Constantes UAT (Embudo Termodinámico)
# ----------------------------------------------------------------------
N_FASES = 8
K_EARLY = 0.967
PHASE_STEP_QUANTUM = 45.0 * K_EARLY       # 43.515°
R_GEOM = 0.2792
ETA_CAUSAL = 0.781
KAPPA_CRIT = 4.978
OVERDRIVE = 5.140
F_BASE = 187.37
FS = 4096
DURACION = 64
SIGMA_TVI = 3.2400
SVR_TARGET = (ETA_CAUSAL * R_GEOM / SIGMA_TVI) * 0.7071
GAMMA_FIJO = 2.08
HIGO_BAND = (227.5, 232.5)

angulos = np.deg2rad(np.arange(N_FASES) * PHASE_STEP_QUANTUM)

# ----------------------------------------------------------------------
# 3. Funciones UAT
# ----------------------------------------------------------------------
class UAT_Engine:
    def __init__(self, epsilon=1e-4, k_early=0.967):
        self.epsilon = epsilon; self.k_early = k_early
        self.total_singularities = 0

    def percudani_whiten(self, signal, fs):
        N = len(signal)
        spec = rfft(signal)
        psd = np.abs(spec)**2
        psd_smooth = uniform_filter1d(psd, size=512, mode='constant')
        D = psd_smooth + self.epsilon * self.k_early
        D_safe = np.where(D > 1e-30, D, 1e-30)
        spec_white = spec / np.sqrt(D_safe)
        out = irfft(spec_white, n=N)
        out -= np.mean(out); std = np.std(out)
        if std > 1e-15: out /= std
        return out

    def uat_coherence(self, x, y, fs, nperseg=8192, noverlap=4096, band=HIGO_BAND):
        step = nperseg - noverlap
        N = len(x)
        n_segments = (N - nperseg) // step + 1
        window = np.hanning(nperseg)
        Pxx = np.zeros(nperseg//2 + 1)
        Pyy = np.zeros(nperseg//2 + 1)
        Pxy = np.zeros(nperseg//2 + 1, dtype=complex)
        for i in range(n_segments):
            start = i * step; end = start + nperseg
            x_seg = x[start:end] * window
            y_seg = y[start:end] * window
            X = rfft(x_seg); Y = rfft(y_seg)
            Pxx += np.abs(X)**2
            Pyy += np.abs(Y)**2
            Pxy += X * np.conj(Y)
        Pxx /= n_segments; Pyy /= n_segments; Pxy /= n_segments
        with np.errstate(divide='ignore', invalid='ignore'):
            coh = np.abs(Pxy)**2 / (Pxx * Pyy)
        f = rfftfreq(nperseg, d=1/fs)
        mask_band = (f >= band[0]) & (f <= band[1])
        if np.any(mask_band):
            idx = np.where(mask_band)[0]
            nan_mask = np.isnan(coh[idx])
            self.total_singularities += np.sum(nan_mask)
            coh[idx] = np.nan_to_num(coh[idx], nan=1.0)
        return f, coh

def calcular_svr(senal, sigma_tvi=SIGMA_TVI):
    rms = np.sqrt(np.mean(senal**2))
    amp_max = np.max(np.abs(senal)) if np.max(np.abs(senal)) > 0 else 1
    rms_norm = rms / amp_max * 0.7071
    return rms_norm / sigma_tvi

def simular_embudo_fijo(senal, n_samples, gamma=GAMMA_FIJO, ruido_base=0.01):
    t = np.linspace(0, DURACION, n_samples)
    senales_frentes = []
    for i in range(N_FASES):
        factor_ruido = ruido_base * (1 + 0.5 * np.abs(np.sin(angulos[i])))
        ruido_fondo = np.random.randn(n_samples) * factor_ruido
        fase_modulada = senal * np.cos(angulos[i]) + ruido_fondo * np.sin(angulos[i])
        senales_frentes.append(fase_modulada)

    pares = np.sum(senales_frentes[::2], axis=0)
    impares = np.sum(senales_frentes[1::2], axis=0)

    ventana = 50
    coherencia_local = np.zeros(n_samples)
    for i in range(ventana, n_samples - ventana):
        corr = np.corrcoef(pares[i-ventana:i+ventana], impares[i-ventana:i+ventana])[0,1]
        coherencia_local[i] = max(0, corr)

    phi = gamma * (OVERDRIVE / KAPPA_CRIT) * coherencia_local
    senal_embudo = pares * np.cos(phi) + impares * np.sin(phi)
    return senal_embudo

# ----------------------------------------------------------------------
# 4. Búsqueda del mejor instante de observación (máxima altitud)
# ----------------------------------------------------------------------
def find_best_observation_time(ra_deg, dec_deg, detector_site, gps_o4a_start=1368960018, search_window_days=365):
    source = SkyCoord(ra=ra_deg*u.deg, dec=dec_deg*u.deg, frame='icrs')
    site = EarthLocation.of_site(detector_site)

    best_alt = -999
    best_gps = gps_o4a_start

    for day_offset in range(0, search_window_days, 1):
        for hour in range(0, 24, 2):
            gps_test = gps_o4a_start + day_offset * 86400 + hour * 3600
            t = Time(gps_test, format='gps', scale='utc')
            frame = AltAz(obstime=t, location=site)
            source_altaz = source.transform_to(frame)
            alt = source_altaz.alt.deg
            if alt > best_alt:
                best_alt = alt
                best_gps = gps_test

    return int(best_gps)

# ----------------------------------------------------------------------
# 5. Función de descarga tolerante a fallos
# ----------------------------------------------------------------------
def fetch_ligo_data_robust(gps_start, duration, fs, max_attempts=5):
    """
    Intenta descargar H1 y L1. Si falla, suma 86400 segundos al GPS
    y vuelve a intentar, hasta max_attempts veces.
    Retorna (h1, l1) o (None, None) si no lo consigue.
    """
    for attempt in range(max_attempts):
        gps_try = gps_start + attempt * 86400
        try:
            h1 = TimeSeries.fetch_open_data('H1', gps_try, gps_try + duration,
                                            sample_rate=16384, verbose=False).resample(fs).value
            l1 = TimeSeries.fetch_open_data('L1', gps_try, gps_try + duration,
                                            sample_rate=16384, verbose=False).resample(fs).value
            print(f"  Segmento encontrado en GPS {gps_try} (intento {attempt+1})")
            return h1, l1
        except Exception:
            print(f"  Intento {attempt+1} en GPS {gps_try} fallido, probando +1 día...")
    return None, None

# ----------------------------------------------------------------------
# 6. Bucle principal sobre candidatos VASCO
# ----------------------------------------------------------------------
engine = UAT_Engine()
results = []

for cand in vasco_candidates:
    print(f"\nProcesando {cand['id']} (RA={cand['ra_deg']:.4f}°, Dec={cand['dec_deg']:.4f}°)...")

    # Mejor instante de observación para H1 y L1
    gps_h1 = find_best_observation_time(cand['ra_deg'], cand['dec_deg'], 'LIGO Hanford Observatory')
    gps_l1 = find_best_observation_time(cand['ra_deg'], cand['dec_deg'], 'LIGO Livingston Observatory')
    gps_obs = int((gps_h1 + gps_l1) / 2)

    # Descargar con tolerancia a fallos
    h1_raw, l1_raw = fetch_ligo_data_robust(gps_obs, DURACION, FS)
    if h1_raw is None:
        print(f"  [!] No se pudo obtener datos para {cand['id']} tras 5 intentos.")
        continue

    min_len = min(len(h1_raw), len(l1_raw))
    h1_raw, l1_raw = h1_raw[:min_len], l1_raw[:min_len]

    # Blanqueamiento
    h1_w = engine.percudani_whiten(h1_raw, FS)
    l1_w = engine.percudani_whiten(l1_raw, FS)

    # Coherencia UAT
    f, coh = engine.uat_coherence(h1_w, l1_w, FS)
    mask = (f >= HIGO_BAND[0]) & (f <= HIGO_BAND[1])
    coh_max = np.max(coh[mask]) if np.any(mask) else 0.0
    sing = engine.total_singularities

    # SVR para H1 y L1 (embudo)
    n_samples = len(h1_w)
    svr_h1 = calcular_svr(simular_embudo_fijo(h1_w, n_samples, gamma=GAMMA_FIJO))
    svr_l1 = calcular_svr(simular_embudo_fijo(l1_w, n_samples, gamma=GAMMA_FIJO))

    results.append({
        'id': cand['id'],
        'gps_obs': gps_obs,
        'coh_max': coh_max,
        'singularities': sing,
        'svr_h1': svr_h1,
        'svr_l1': svr_l1
    })

    print(f"  SVR H1: {svr_h1:.6f} | SVR L1: {svr_l1:.6f} | Coh máx: {coh_max:.4f} | Sing: {sing}")

# ----------------------------------------------------------------------
# 7. Resumen final
# ----------------------------------------------------------------------
print("\n" + "="*75)
print("RESUMEN DE CORRELACIÓN VASCO-LIGO")
print("="*75)
print(f"SVR objetivo teórico: {SVR_TARGET:.6f}")
print(f"γ fijo: {GAMMA_FIJO}")
print()
for r in results:
    delta_h1 = r['svr_h1'] - SVR_TARGET
    delta_l1 = r['svr_l1'] - SVR_TARGET
    flag_h1 = "⬆ ANOMALÍA" if abs(delta_h1) > 0.005 else "✓ Normal"
    flag_l1 = "⬆ ANOMALÍA" if abs(delta_l1) > 0.005 else "✓ Normal"
    print(f"{r['id']}: SVR H1={r['svr_h1']:.6f} ({flag_h1}) | SVR L1={r['svr_l1']:.6f} ({flag_l1}) | Coh={r['coh_max']:.4f}")

anomalos_h1 = [r for r in results if abs(r['svr_h1'] - SVR_TARGET) > 0.005]
anomalos_l1 = [r for r in results if abs(r['svr_l1'] - SVR_TARGET) > 0.005]
print(f"\n{len(anomalos_h1)}/{len(results)} candidatos muestran SVR anómala en H1.")
print(f"{len(anomalos_l1)}/{len(results)} candidatos muestran SVR anómala en L1.")
print("="*75)

# -*- coding: utf-8 -*-
# ======================================================================
# PERCUDANI AUTHORSHIP – Resonant Hunter v9.1 (Morfología VASCO-02)
# Segmento GPS 1376930418 – Livingston L1 – Embudo γ=2.08
# DOIs permanentes en salida.
# ======================================================================
!pip install -q numpy scipy gwpy matplotlib

import numpy as np
from numpy.fft import rfft, irfft, rfftfreq
from scipy.ndimage import uniform_filter1d
import matplotlib.pyplot as plt
from gwpy.timeseries import TimeSeries

# ----------------------------------------------------------------------
# DOIs de la Investigación
# ----------------------------------------------------------------------
DOI_RH  = "10.5281/zenodo.18446712"
DOI_UAT = "10.5281/zenodo.17729221"
DOI_UPC = "10.5281/zenodo.18210808"

print("="*75)
print(f"PERCUDANI AUTHORSHIP - Resonant Hunter v9.1 (VASCO-02)")
print(f"DOI RH: {DOI_RH} | DOI UAT: {DOI_UAT} | DOI UPC: {DOI_UPC}")
print("="*75)

# ----------------------------------------------------------------------
# 1. Parámetros UAT / Embudo
# ----------------------------------------------------------------------
N_FASES = 8
K_EARLY = 0.967
PHASE_STEP_QUANTUM = 45.0 * K_EARLY       # 43.515°
R_GEOM = 0.2791
ETA_CAUSAL = 0.781
KAPPA_CRIT = 4.978
OVERDRIVE = 5.140
F_BASE = 187.37
FS = 4096
DURACION = 64
SIGMA_TVI = 3.2400
SVR_TARGET = (ETA_CAUSAL * R_GEOM / SIGMA_TVI) * 0.7071
GAMMA_FIJO = 2.08
HIGO_BAND = (227.5, 232.5)

GPS_VASCO02 = 1376930418   # Segmento donde VASCO-02 está en el cénit de L1

# ----------------------------------------------------------------------
# 2. UAT Engine (coherencia con restauración)
# ----------------------------------------------------------------------
class UAT_Engine:
    def __init__(self, epsilon=1e-4, k_early=0.967):
        self.epsilon = epsilon
        self.k_early = k_early
        self.total_singularities = 0

    def percudani_whiten(self, signal, fs):
        N = len(signal)
        spec = rfft(signal)
        psd = np.abs(spec)**2
        psd_smooth = uniform_filter1d(psd, size=512, mode='constant')
        D = psd_smooth + self.epsilon * self.k_early
        D_safe = np.where(D > 1e-30, D, 1e-30)
        spec_white = spec / np.sqrt(D_safe)
        out = irfft(spec_white, n=N)
        out -= np.mean(out)
        std = np.std(out)
        if std > 1e-15:
            out /= std
        return out

    def uat_coherence(self, x, y, fs, nperseg=8192, noverlap=4096, band=HIGO_BAND):
        step = nperseg - noverlap
        N = len(x)
        n_segments = (N - nperseg) // step + 1
        window = np.hanning(nperseg)
        Pxx = np.zeros(nperseg//2 + 1)
        Pyy = np.zeros(nperseg//2 + 1)
        Pxy = np.zeros(nperseg//2 + 1, dtype=complex)
        for i in range(n_segments):
            start = i * step
            end = start + nperseg
            x_seg = x[start:end] * window
            y_seg = y[start:end] * window
            X = rfft(x_seg)
            Y = rfft(y_seg)
            Pxx += np.abs(X)**2
            Pyy += np.abs(Y)**2
            Pxy += X * np.conj(Y)
        Pxx /= n_segments
        Pyy /= n_segments
        Pxy /= n_segments
        with np.errstate(divide='ignore', invalid='ignore'):
            coh = np.abs(Pxy)**2 / (Pxx * Pyy)
        f = rfftfreq(nperseg, d=1/fs)
        mask_band = (f >= band[0]) & (f <= band[1])
        if np.any(mask_band):
            idx = np.where(mask_band)[0]
            nan_mask = np.isnan(coh[idx])
            self.total_singularities += np.sum(nan_mask)
            coh[idx] = np.nan_to_num(coh[idx], nan=1.0)
        return f, coh

# ----------------------------------------------------------------------
# 3. Embudo Termodinámico
# ----------------------------------------------------------------------
angulos = np.deg2rad(np.arange(N_FASES) * PHASE_STEP_QUANTUM)

def simular_embudo_fijo(senal, n_samples, gamma=GAMMA_FIJO, ruido_base=0.01):
    senales_frentes = []
    for i in range(N_FASES):
        factor_ruido = ruido_base * (1 + 0.5 * np.abs(np.sin(angulos[i])))
        ruido_fondo = np.random.randn(n_samples) * factor_ruido
        fase_modulada = senal * np.cos(angulos[i]) + ruido_fondo * np.sin(angulos[i])
        senales_frentes.append(fase_modulada)

    pares = np.sum(senales_frentes[::2], axis=0)
    impares = np.sum(senales_frentes[1::2], axis=0)

    ventana = 50
    coherencia_local = np.zeros(n_samples)
    for i in range(ventana, n_samples - ventana):
        corr = np.corrcoef(pares[i-ventana:i+ventana], impares[i-ventana:i+ventana])[0,1]
        coherencia_local[i] = max(0, corr)

    phi = gamma * (OVERDRIVE / KAPPA_CRIT) * coherencia_local
    return pares * np.cos(phi) + impares * np.sin(phi)

def calcular_svr(senal, sigma_tvi=SIGMA_TVI):
    rms = np.sqrt(np.mean(senal**2))
    amp_max = np.max(np.abs(senal)) if np.max(np.abs(senal)) > 0 else 1
    rms_norm = rms / amp_max * 0.7071
    return rms_norm / sigma_tvi

# ----------------------------------------------------------------------
# 4. Adquisición y procesamiento de L1
# ----------------------------------------------------------------------
print(f"Descargando L1 en GPS {GPS_VASCO02}...")
l1_raw = TimeSeries.fetch_open_data('L1', GPS_VASCO02, GPS_VASCO02 + DURACION,
                                    sample_rate=16384, verbose=False).resample(FS).value
engine = UAT_Engine()
l1_white = engine.percudani_whiten(l1_raw, FS)

# Coherencia (necesitamos H1 para coherencia cruzada; usaremos H1 del mismo segmento)
h1_raw = TimeSeries.fetch_open_data('H1', GPS_VASCO02, GPS_VASCO02 + DURACION,
                                    sample_rate=16384, verbose=False).resample(FS).value
min_len = min(len(h1_raw), len(l1_raw))
h1_white = engine.percudani_whiten(h1_raw[:min_len], FS)
l1_white = engine.percudani_whiten(l1_raw[:min_len], FS)

f, coh = engine.uat_coherence(h1_white, l1_white, FS)
mask = (f >= HIGO_BAND[0]) & (f <= HIGO_BAND[1])
coh_max = np.max(coh[mask]) if np.any(mask) else 0.0
sing = engine.total_singularities

# Embudo sobre L1
n_samples = len(l1_white)
senal_embudo = simular_embudo_fijo(l1_white, n_samples, gamma=GAMMA_FIJO)
svr_l1 = calcular_svr(senal_embudo)

# TVI (como en análisis previos)
tvi_l1 = (np.angle(senal_embudo) / (2*np.pi)) * K_EARLY * (1 + 0.046 * (GPS_VASCO02 - 1369483218)/86400.0)
tvi_std = np.std(tvi_l1)

print(f"\n--- MÉTRICAS FINALES ---")
print(f"Coherencia máxima en banda Higo: {coh_max:.4f}")
print(f"Singularidades restauradas: {sing}")
print(f"SVR L1 (embudo γ=2.08): {svr_l1:.6f} (objetivo {SVR_TARGET:.6f})")
print(f"σ_TVI (L1): {tvi_std:.4f}")

# ----------------------------------------------------------------------
# 5. Visualización
# ----------------------------------------------------------------------
fig, axes = plt.subplots(2, 2, figsize=(14, 10))
fig.suptitle(f'Resonant Hunter v9.1 – VASCO-02 (GPS {GPS_VASCO02})', fontsize=14)

# Coherencia
axes[0,0].plot(f, coh)
axes[0,0].axvline(HIGO_BAND[0], color='red', linestyle='--')
axes[0,0].axvline(HIGO_BAND[1], color='red', linestyle='--')
axes[0,0].set_xlim(200, 260)
axes[0,0].set_ylim(0, 1.1)
axes[0,0].set_title(f'Coherencia UAT (máx={coh_max:.4f})')
axes[0,0].set_xlabel('Frecuencia (Hz)')
axes[0,0].set_ylabel('Coherencia')

# Forma de onda embudo
axes[0,1].plot(senal_embudo[:2000], linewidth=0.5)
axes[0,1].set_title('Embudo termodinámico (primeras 2000 muestras)')

# TVI
axes[1,0].plot(tvi_l1[:2000], linewidth=0.5)
axes[1,0].axhline(y=0, color='black', linestyle='--')
axes[1,0].set_title(f'TVI (σ={tvi_std:.4f})')

# Espectro de frecuencias
spec = np.abs(rfft(l1_white))
freq = rfftfreq(len(l1_white), d=1/FS)
axes[1,1].plot(freq, spec/np.max(spec))
axes[1,1].axvline(F_BASE, color='green', linestyle=':', label=f'f_UAT={F_BASE} Hz')
axes[1,1].set_xlim(0, 500)
axes[1,1].set_title('Espectro blanqueado')
axes[1,1].legend()

plt.tight_layout()
plt.savefig('vasco02_morfologia.png', dpi=150)
plt.show()

# -*- coding: utf-8 -*-
# ======================================================================
# PERCUDANI AUTHORSHIP – Resonant Hunter v9.1 (Morfología VASCO-06)
# Segmento GPS 1379414418 – Livingston L1 – Embudo γ=2.08
# DOIs permanentes en salida.
# ======================================================================
!pip install -q numpy scipy gwpy matplotlib

import numpy as np
from numpy.fft import rfft, irfft, rfftfreq
from scipy.ndimage import uniform_filter1d
import matplotlib.pyplot as plt
from gwpy.timeseries import TimeSeries

# ----------------------------------------------------------------------
# DOIs de la Investigación
# ----------------------------------------------------------------------
DOI_RH  = "10.5281/zenodo.18446712"
DOI_UAT = "10.5281/zenodo.17729221"
DOI_UPC = "10.5281/zenodo.18210808"

print("="*75)
print(f"PERCUDANI AUTHORSHIP - Resonant Hunter v9.1 (VASCO-06)")
print(f"DOI RH: {DOI_RH} | DOI UAT: {DOI_UAT} | DOI UPC: {DOI_UPC}")
print("="*75)

# ----------------------------------------------------------------------
# 1. Parámetros UAT / Embudo
# ----------------------------------------------------------------------
N_FASES = 8
K_EARLY = 0.967
PHASE_STEP_QUANTUM = 45.0 * K_EARLY       # 43.515°
R_GEOM = 0.2791
ETA_CAUSAL = 0.781
KAPPA_CRIT = 4.978
OVERDRIVE = 5.140
F_BASE = 187.37
FS = 4096
DURACION = 64
SIGMA_TVI = 3.2400
SVR_TARGET = (ETA_CAUSAL * R_GEOM / SIGMA_TVI) * 0.7071
GAMMA_FIJO = 2.08
HIGO_BAND = (227.5, 232.5)

GPS_VASCO06 = 1379414418   # Segmento donde VASCO-06 está en el cénit de L1

# ----------------------------------------------------------------------
# 2. UAT Engine (coherencia con restauración)
# ----------------------------------------------------------------------
class UAT_Engine:
    def __init__(self, epsilon=1e-4, k_early=0.967):
        self.epsilon = epsilon
        self.k_early = k_early
        self.total_singularities = 0

    def percudani_whiten(self, signal, fs):
        N = len(signal)
        spec = rfft(signal)
        psd = np.abs(spec)**2
        psd_smooth = uniform_filter1d(psd, size=512, mode='constant')
        D = psd_smooth + self.epsilon * self.k_early
        D_safe = np.where(D > 1e-30, D, 1e-30)
        spec_white = spec / np.sqrt(D_safe)
        out = irfft(spec_white, n=N)
        out -= np.mean(out)
        std = np.std(out)
        if std > 1e-15:
            out /= std
        return out

    def uat_coherence(self, x, y, fs, nperseg=8192, noverlap=4096, band=HIGO_BAND):
        step = nperseg - noverlap
        N = len(x)
        n_segments = (N - nperseg) // step + 1
        window = np.hanning(nperseg)
        Pxx = np.zeros(nperseg//2 + 1)
        Pyy = np.zeros(nperseg//2 + 1)
        Pxy = np.zeros(nperseg//2 + 1, dtype=complex)
        for i in range(n_segments):
            start = i * step
            end = start + nperseg
            x_seg = x[start:end] * window
            y_seg = y[start:end] * window
            X = rfft(x_seg)
            Y = rfft(y_seg)
            Pxx += np.abs(X)**2
            Pyy += np.abs(Y)**2
            Pxy += X * np.conj(Y)
        Pxx /= n_segments
        Pyy /= n_segments
        Pxy /= n_segments
        with np.errstate(divide='ignore', invalid='ignore'):
            coh = np.abs(Pxy)**2 / (Pxx * Pyy)
        f = rfftfreq(nperseg, d=1/fs)
        mask_band = (f >= band[0]) & (f <= band[1])
        if np.any(mask_band):
            idx = np.where(mask_band)[0]
            nan_mask = np.isnan(coh[idx])
            self.total_singularities += np.sum(nan_mask)
            coh[idx] = np.nan_to_num(coh[idx], nan=1.0)
        return f, coh

# ----------------------------------------------------------------------
# 3. Embudo Termodinámico
# ----------------------------------------------------------------------
angulos = np.deg2rad(np.arange(N_FASES) * PHASE_STEP_QUANTUM)

def simular_embudo_fijo(senal, n_samples, gamma=GAMMA_FIJO, ruido_base=0.01):
    senales_frentes = []
    for i in range(N_FASES):
        factor_ruido = ruido_base * (1 + 0.5 * np.abs(np.sin(angulos[i])))
        ruido_fondo = np.random.randn(n_samples) * factor_ruido
        fase_modulada = senal * np.cos(angulos[i]) + ruido_fondo * np.sin(angulos[i])
        senales_frentes.append(fase_modulada)

    pares = np.sum(senales_frentes[::2], axis=0)
    impares = np.sum(senales_frentes[1::2], axis=0)

    ventana = 50
    coherencia_local = np.zeros(n_samples)
    for i in range(ventana, n_samples - ventana):
        corr = np.corrcoef(pares[i-ventana:i+ventana], impares[i-ventana:i+ventana])[0,1]
        coherencia_local[i] = max(0, corr)

    phi = gamma * (OVERDRIVE / KAPPA_CRIT) * coherencia_local
    return pares * np.cos(phi) + impares * np.sin(phi)

def calcular_svr(senal, sigma_tvi=SIGMA_TVI):
    rms = np.sqrt(np.mean(senal**2))
    amp_max = np.max(np.abs(senal)) if np.max(np.abs(senal)) > 0 else 1
    rms_norm = rms / amp_max * 0.7071
    return rms_norm / sigma_tvi

# ----------------------------------------------------------------------
# 4. Adquisición y procesamiento de L1
# ----------------------------------------------------------------------
print(f"Descargando L1 en GPS {GPS_VASCO06}...")
l1_raw = TimeSeries.fetch_open_data('L1', GPS_VASCO06, GPS_VASCO06 + DURACION,
                                    sample_rate=16384, verbose=False).resample(FS).value
engine = UAT_Engine()
l1_white = engine.percudani_whiten(l1_raw, FS)

# Coherencia (necesitamos H1 para coherencia cruzada; usaremos H1 del mismo segmento)
h1_raw = TimeSeries.fetch_open_data('H1', GPS_VASCO06, GPS_VASCO06 + DURACION,
                                    sample_rate=16384, verbose=False).resample(FS).value
min_len = min(len(h1_raw), len(l1_raw))
h1_white = engine.percudani_whiten(h1_raw[:min_len], FS)
l1_white = engine.percudani_whiten(l1_raw[:min_len], FS)

f, coh = engine.uat_coherence(h1_white, l1_white, FS)
mask = (f >= HIGO_BAND[0]) & (f <= HIGO_BAND[1])
coh_max = np.max(coh[mask]) if np.any(mask) else 0.0
sing = engine.total_singularities

# Embudo sobre L1
n_samples = len(l1_white)
senal_embudo = simular_embudo_fijo(l1_white, n_samples, gamma=GAMMA_FIJO)
svr_l1 = calcular_svr(senal_embudo)

# TVI (como en análisis previos)
tvi_l1 = (np.angle(senal_embudo) / (2*np.pi)) * K_EARLY * (1 + 0.046 * (GPS_VASCO06 - 1369483218)/86400.0)
tvi_std = np.std(tvi_l1)

print(f"\n--- MÉTRICAS FINALES ---")
print(f"Coherencia máxima en banda Higo: {coh_max:.4f}")
print(f"Singularidades restauradas: {sing}")
print(f"SVR L1 (embudo γ=2.08): {svr_l1:.6f} (objetivo {SVR_TARGET:.6f})")
print(f"σ_TVI (L1): {tvi_std:.4f}")

# ----------------------------------------------------------------------
# 5. Visualización
# ----------------------------------------------------------------------
fig, axes = plt.subplots(2, 2, figsize=(14, 10))
fig.suptitle(f'Resonant Hunter v9.1 – VASCO-06 (GPS {GPS_VASCO06})', fontsize=14)

# Coherencia
axes[0,0].plot(f, coh)
axes[0,0].axvline(HIGO_BAND[0], color='red', linestyle='--')
axes[0,0].axvline(HIGO_BAND[1], color='red', linestyle='--')
axes[0,0].set_xlim(200, 260)
axes[0,0].set_ylim(0, 1.1)
axes[0,0].set_title(f'Coherencia UAT (máx={coh_max:.4f})')
axes[0,0].set_xlabel('Frecuencia (Hz)')
axes[0,0].set_ylabel('Coherencia')

# Forma de onda embudo
axes[0,1].plot(senal_embudo[:2000], linewidth=0.5)
axes[0,1].set_title('Embudo termodinámico (primeras 2000 muestras)')

# TVI
axes[1,0].plot(tvi_l1[:2000], linewidth=0.5)
axes[1,0].axhline(y=0, color='black', linestyle='--')
axes[1,0].set_title(f'TVI (σ={tvi_std:.4f})')

# Espectro de frecuencias
spec = np.abs(rfft(l1_white))
freq = rfftfreq(len(l1_white), d=1/FS)
axes[1,1].plot(freq, spec/np.max(spec))
axes[1,1].axvline(F_BASE, color='green', linestyle=':', label=f'f_UAT={F_BASE} Hz')
axes[1,1].set_xlim(0, 500)
axes[1,1].set_title('Espectro blanqueado')
axes[1,1].legend()

plt.tight_layout()
plt.savefig('vasco06_morfologia.png', dpi=150)
plt.show()

# -*- coding: utf-8 -*-
# ======================================================================
# PERCUDANI AUTHORSHIP – Iteración Final: Espectro Blanco de VASCO‑02
# Segmento GPS 1376930418 – Livingston L1 – Verificación de 187.37 Hz
# ======================================================================
!pip install -q numpy scipy gwpy matplotlib

import numpy as np
from numpy.fft import rfft, rfftfreq
from scipy.ndimage import uniform_filter1d
import matplotlib.pyplot as plt
from gwpy.timeseries import TimeSeries

# ----------------------------------------------------------------------
# DOIs de la Investigación
# ----------------------------------------------------------------------
DOI_RH  = "10.5281/zenodo.18446712"
DOI_UAT = "10.5281/zenodo.17729221"
DOI_UPC = "10.5281/zenodo.18210808"

print("="*75)
print(f"PERCUDANI AUTHORSHIP – Espectro Blanco Final (VASCO‑02)")
print(f"DOI RH: {DOI_RH} | DOI UAT: {DOI_UAT} | DOI UPC: {DOI_UPC}")
print("="*75)

# Parámetros
GPS_VASCO02 = 1376930418
FS = 4096
DURACION = 64
F_BASE = 187.37

# Descargar L1
print(f"Descargando L1 en GPS {GPS_VASCO02}...")
l1_raw = TimeSeries.fetch_open_data('L1', GPS_VASCO02, GPS_VASCO02 + DURACION,
                                    sample_rate=16384, verbose=False).resample(FS).value

# Blanqueamiento Percudani (idéntico al de los análisis anteriores)
epsilon = 1e-4
k_early = 0.967
N = len(l1_raw)
spec = rfft(l1_raw)
psd = np.abs(spec)**2
psd_smooth = uniform_filter1d(psd, size=512, mode='constant')
D = psd_smooth + epsilon * k_early
D_safe = np.where(D > 1e-30, D, 1e-30)
spec_white = spec / np.sqrt(D_safe)
l1_white = np.fft.irfft(spec_white, n=N)
l1_white -= np.mean(l1_white)
l1_white /= np.std(l1_white)

# Espectro blanqueado
spec_w = np.abs(rfft(l1_white))
freq = rfftfreq(N, d=1/FS)

# Encontrar el pico más cercano a 187.37 Hz
idx_peak = np.argmin(np.abs(freq - F_BASE))
peak_amplitude = spec_w[idx_peak] / np.max(spec_w)

# Graficar
plt.figure(figsize=(12, 6))
plt.plot(freq, spec_w / np.max(spec_w), color='darkblue', linewidth=0.8, label='Espectro blanqueado (L1)')
plt.axvline(F_BASE, color='red', linestyle='--', linewidth=1.5, label=f'Frecuencia UAT = {F_BASE} Hz')
plt.axhline(0.5, color='gray', linestyle=':', alpha=0.5)

# Resaltar el pico
plt.scatter(freq[idx_peak], peak_amplitude, color='red', s=80, zorder=5,
            label=f'Pico a {freq[idx_peak]:.2f} Hz (ampl. normalizada = {peak_amplitude:.4f})')

plt.xlim(0, 500)
plt.ylim(0, 1.05)
plt.xlabel('Frecuencia (Hz)')
plt.ylabel('Amplitud normalizada')
plt.title('Espectro Blanco Percudani – VASCO‑02 (L1, GPS 1376930418)')
plt.legend()
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.savefig('vasco02_espectro_final.png', dpi=200)
plt.show()

# Reporte
print(f"\n--- VERIFICACIÓN DEL PICO UAT ---")
print(f"Frecuencia objetivo: {F_BASE} Hz")
print(f"Frecuencia del pico más cercano: {freq[idx_peak]:.2f} Hz")
print(f"Amplitud normalizada: {peak_amplitude:.4f}")
print(f"¿Es una línea instrumental? {peak_amplitude > 0.9 and 'Probablemente SÍ' or 'Probablemente NO'}")
print("="*75)

# -*- coding: utf-8 -*-
# ======================================================================
# PERCUDANI AUTHORSHIP – Catálogo UAT-VASCO (10 candidatos)
# Resonant Hunter v9.1 – Embudo Termodinámico (γ=2.08)
# Extracción morfológica completa: coherencia, SVR, TVI, espectro
# ======================================================================
!pip install -q numpy scipy gwpy matplotlib astropy

import numpy as np
from numpy.fft import rfft, irfft, rfftfreq
from scipy.ndimage import uniform_filter1d
import matplotlib.pyplot as plt
from gwpy.timeseries import TimeSeries
from astropy.coordinates import SkyCoord, EarthLocation, AltAz
from astropy.time import Time
import astropy.units as u
import os, time

# ----------------------------------------------------------------------
# DOIs
# ----------------------------------------------------------------------
DOI_RH  = "10.5281/zenodo.18446712"
DOI_UAT = "10.5281/zenodo.17729221"
DOI_UPC = "10.5281/zenodo.18210808"

print("="*75)
print(f"PERCUDANI AUTHORSHIP – Catálogo UAT-VASCO (10 candidatos)")
print(f"DOI RH: {DOI_RH} | DOI UAT: {DOI_UAT} | DOI UPC: {DOI_UPC}")
print("="*75)

# ----------------------------------------------------------------------
# 1. Tabla de candidatos VASCO
# ----------------------------------------------------------------------
vasco_candidates = [
    {"id": "VASCO-01", "ra_deg": 99.0875, "dec_deg": +2.4339},
    {"id": "VASCO-02", "ra_deg": 296.3001, "dec_deg": -14.1758},
    {"id": "VASCO-03", "ra_deg": 14.5621, "dec_deg": +45.8992},
    {"id": "VASCO-04", "ra_deg": 134.1120, "dec_deg": -8.4410},
    {"id": "VASCO-05", "ra_deg": 210.5543, "dec_deg": +33.1095},
    {"id": "VASCO-06", "ra_deg": 55.7892, "dec_deg": -22.5034},
    {"id": "VASCO-07", "ra_deg": 315.0045, "dec_deg": +60.1128},
    {"id": "VASCO-08", "ra_deg": 88.3412, "dec_deg": +15.7761},
    {"id": "VASCO-09", "ra_deg": 275.9088, "dec_deg": -5.3341},
    {"id": "VASCO-10", "ra_deg": 102.4456, "dec_deg": +48.2010},
]

# ----------------------------------------------------------------------
# 2. Constantes UAT / Embudo
# ----------------------------------------------------------------------
N_FASES = 8
K_EARLY = 0.967
PHASE_STEP_QUANTUM = 45.0 * K_EARLY
R_GEOM = 0.2791
ETA_CAUSAL = 0.781
KAPPA_CRIT = 4.978
OVERDRIVE = 5.140
F_BASE = 187.37
FS = 4096
DURACION = 64
SIGMA_TVI = 3.2400
SVR_TARGET = (ETA_CAUSAL * R_GEOM / SIGMA_TVI) * 0.7071
GAMMA_FIJO = 2.08
HIGO_BAND = (227.5, 232.5)

angulos = np.deg2rad(np.arange(N_FASES) * PHASE_STEP_QUANTUM)

# ----------------------------------------------------------------------
# 3. UAT Engine
# ----------------------------------------------------------------------
class UAT_Engine:
    def __init__(self, epsilon=1e-4, k_early=0.967):
        self.epsilon = epsilon; self.k_early = k_early
        self.total_singularities = 0

    def percudani_whiten(self, signal, fs):
        N = len(signal)
        spec = rfft(signal)
        psd = np.abs(spec)**2
        psd_smooth = uniform_filter1d(psd, size=512, mode='constant')
        D = psd_smooth + self.epsilon * self.k_early
        D_safe = np.where(D > 1e-30, D, 1e-30)
        spec_white = spec / np.sqrt(D_safe)
        out = irfft(spec_white, n=N)
        out -= np.mean(out); std = np.std(out)
        if std > 1e-15: out /= std
        return out

    def uat_coherence(self, x, y, fs, nperseg=8192, noverlap=4096, band=HIGO_BAND):
        step = nperseg - noverlap
        N = len(x)
        n_segments = (N - nperseg) // step + 1
        window = np.hanning(nperseg)
        Pxx = np.zeros(nperseg//2 + 1)
        Pyy = np.zeros(nperseg//2 + 1)
        Pxy = np.zeros(nperseg//2 + 1, dtype=complex)
        for i in range(n_segments):
            start = i * step; end = start + nperseg
            x_seg = x[start:end] * window
            y_seg = y[start:end] * window
            X = rfft(x_seg); Y = rfft(y_seg)
            Pxx += np.abs(X)**2
            Pyy += np.abs(Y)**2
            Pxy += X * np.conj(Y)
        Pxx /= n_segments; Pyy /= n_segments; Pxy /= n_segments
        with np.errstate(divide='ignore', invalid='ignore'):
            coh = np.abs(Pxy)**2 / (Pxx * Pyy)
        f = rfftfreq(nperseg, d=1/fs)
        mask_band = (f >= band[0]) & (f <= band[1])
        if np.any(mask_band):
            idx = np.where(mask_band)[0]
            nan_mask = np.isnan(coh[idx])
            self.total_singularities += np.sum(nan_mask)
            coh[idx] = np.nan_to_num(coh[idx], nan=1.0)
        return f, coh

# ----------------------------------------------------------------------
# 4. Embudo Termodinámico
# ----------------------------------------------------------------------
def simular_embudo_fijo(senal, n_samples, gamma=GAMMA_FIJO, ruido_base=0.01):
    senales_frentes = []
    for i in range(N_FASES):
        factor_ruido = ruido_base * (1 + 0.5 * np.abs(np.sin(angulos[i])))
        ruido_fondo = np.random.randn(n_samples) * factor_ruido
        fase_modulada = senal * np.cos(angulos[i]) + ruido_fondo * np.sin(angulos[i])
        senales_frentes.append(fase_modulada)

    pares = np.sum(senales_frentes[::2], axis=0)
    impares = np.sum(senales_frentes[1::2], axis=0)

    ventana = 50
    coherencia_local = np.zeros(n_samples)
    for i in range(ventana, n_samples - ventana):
        corr = np.corrcoef(pares[i-ventana:i+ventana], impares[i-ventana:i+ventana])[0,1]
        coherencia_local[i] = max(0, corr)

    phi = gamma * (OVERDRIVE / KAPPA_CRIT) * coherencia_local
    return pares * np.cos(phi) + impares * np.sin(phi)

def calcular_svr(senal, sigma_tvi=SIGMA_TVI):
    rms = np.sqrt(np.mean(senal**2))
    amp_max = np.max(np.abs(senal)) if np.max(np.abs(senal)) > 0 else 1
    rms_norm = rms / amp_max * 0.7071
    return rms_norm / sigma_tvi

# ----------------------------------------------------------------------
# 5. Búsqueda del mejor instante de observación
# ----------------------------------------------------------------------
def find_best_observation_time(ra_deg, dec_deg, detector_site, gps_o4a_start=1368960018):
    source = SkyCoord(ra=ra_deg*u.deg, dec=dec_deg*u.deg, frame='icrs')
    site = EarthLocation.of_site(detector_site)
    best_alt = -999; best_gps = gps_o4a_start
    for day_offset in range(0, 365, 1):
        for hour in range(0, 24, 2):
            gps_test = gps_o4a_start + day_offset*86400 + hour*3600
            t = Time(gps_test, format='gps', scale='utc')
            frame = AltAz(obstime=t, location=site)
            alt = source.transform_to(frame).alt.deg
            if alt > best_alt:
                best_alt = alt; best_gps = gps_test
    return int(best_gps)

# ----------------------------------------------------------------------
# 6. Descarga tolerante a fallos
# ----------------------------------------------------------------------
def fetch_ligo_data_robust(gps_start, duration, fs, max_attempts=5):
    for attempt in range(max_attempts):
        gps_try = gps_start + attempt*86400
        try:
            h1 = TimeSeries.fetch_open_data('H1', gps_try, gps_try+duration,
                                            sample_rate=16384, verbose=False).resample(fs).value
            l1 = TimeSeries.fetch_open_data('L1', gps_try, gps_try+duration,
                                            sample_rate=16384, verbose=False).resample(fs).value
            print(f"  Segmento GPS {gps_try} (intento {attempt+1})")
            return h1, l1
        except Exception:
            print(f"  Intento {attempt+1} fallido, probando +1 día...")
    return None, None

# ----------------------------------------------------------------------
# 7. Bucle principal – Catálogo
# ----------------------------------------------------------------------
engine = UAT_Engine()
catalogo = []

for cand in vasco_candidates:
    print(f"\nProcesando {cand['id']} (RA={cand['ra_deg']:.4f}°, Dec={cand['dec_deg']:.4f}°)...")
    gps_h1 = find_best_observation_time(cand['ra_deg'], cand['dec_deg'], 'LIGO Hanford Observatory')
    gps_l1 = find_best_observation_time(cand['ra_deg'], cand['dec_deg'], 'LIGO Livingston Observatory')
    gps_obs = int((gps_h1 + gps_l1)/2)

    h1_raw, l1_raw = fetch_ligo_data_robust(gps_obs, DURACION, FS)
    if h1_raw is None:
        print(f"  [!] {cand['id']} sin datos tras 5 intentos.")
        continue

    min_len = min(len(h1_raw), len(l1_raw))
    h1_w = engine.percudani_whiten(h1_raw[:min_len], FS)
    l1_w = engine.percudani_whiten(l1_raw[:min_len], FS)

    # Coherencia
    f, coh = engine.uat_coherence(h1_w, l1_w, FS)
    mask = (f >= HIGO_BAND[0]) & (f <= HIGO_BAND[1])
    coh_max = np.max(coh[mask]) if np.any(mask) else 0.0
    sing = engine.total_singularities

    # SVR y TVI en L1
    n_samples = len(l1_w)
    senal_embudo = simular_embudo_fijo(l1_w, n_samples, gamma=GAMMA_FIJO)
    svr_l1 = calcular_svr(senal_embudo)
    tvi_l1 = (np.angle(senal_embudo)/(2*np.pi)) * K_EARLY * (1 + 0.046*(gps_obs - 1369483218)/86400.0)
    tvi_std = np.std(tvi_l1)

    # Espectro blanqueado – verificación de pico UAT
    spec_w = np.abs(rfft(l1_w))
    freq = rfftfreq(len(l1_w), d=1/FS)
    idx_peak = np.argmin(np.abs(freq - F_BASE))
    amp_peak = spec_w[idx_peak] / np.max(spec_w)

    catalogo.append({
        'id': cand['id'],
        'ra_deg': cand['ra_deg'],
        'dec_deg': cand['dec_deg'],
        'gps_obs': gps_obs,
        'coh_max': coh_max,
        'singularities': sing,
        'svr_l1': svr_l1,
        'tvi_std': tvi_std,
        'amp_187Hz': amp_peak,
        'freq_peak': freq[idx_peak]
    })

    print(f"  Coh={coh_max:.4f} | SVR={svr_l1:.6f} | TVI_std={tvi_std:.4f} | Amp_187={amp_peak:.4f}")

# ----------------------------------------------------------------------
# 8. Resumen final
# ----------------------------------------------------------------------
print("\n" + "="*90)
print("CATÁLOGO UAT-VASCO (Resonant Hunter v9.1)")
print(f"SVR objetivo teórico: {SVR_TARGET:.6f}")
print(f"{'ID':<12} {'RA':>8} {'Dec':>8} {'Coh_max':>9} {'SVR_L1':>9} {'TVI_std':>9} {'Amp_187':>9}")
print("-"*90)
for c in catalogo:
    print(f"{c['id']:<12} {c['ra_deg']:8.3f} {c['dec_deg']:8.3f} {c['coh_max']:9.4f} {c['svr_l1']:9.6f} {c['tvi_std']:9.4f} {c['amp_187Hz']:9.4f}")
print("="*90)